version: '3'

services:
  #nginx:
  #   image: nginx:1.13-alpine
  #   container_name: nginx01
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/processos
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./nginx/certs:/etc/nginx/certs
  #     #- ./nginx
  #   depends_on:
  #     - web
  db:
    image: postgres:9.6
    env_file: dev-env
  web:
    build: .
    command: ["sh", "start.sh"]
    volumes:
      - .:/processos
    expose:
       - "8000"
    depends_on:
      - db