version: '3'

services:
  #nginx:
  #   image: nginx:1.13-alpine
  #   container_name: nginx01
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/processos
  #     - ./nginx:/etc/nginx/conf.d
  #     - ./nginx/certs:/etc/nginx/certs
       #- ./nginx
  #   depends_on:
  #     - web
  db:
    image: postgres:9.6
    env_file: dev-env
  redis:
    image: "redis:alpine"
  web:
    build: .
    env_file: dev-env
    command: ["sh", "start.sh"]
    volumes:
      - .:/processos
    ports:
      - "80:8000"
    depends_on:
      - db
      - redis
    celery:
    build: .
    command: celery -A proj worker -l info
    volumes:
      - .:/processos
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A proj beat -l info
    volumes:
      - .:/processos
    depends_on:
      - db
      - redis