# Generated by Django 2.2.12 on 2020-04-25 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.TextField()),
                ('numero', models.TextField()),
                ('descricao', models.TextField()),
                ('incidente_id', models.TextField(blank=True, default='id')),
                ('data_atualizacao', models.TextField(blank=True, default='03/10/1995')),
                ('descricao_atualizacao', models.TextField(blank=True, default='desc_at', null=True)),
                ('emails', models.TextField(blank=True, default='processosglobobsa@gmail.com', null=True)),
                ('url', models.TextField(blank=True, default='url')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
