# Generated by Django 2.2.12 on 2020-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.TextField()),
                ('numero', models.TextField()),
                ('descricao', models.TextField()),
                ('incidente_id', models.TextField()),
                ('data_atualizacao', models.TextField()),
                ('descricao_atualizacao', models.TextField()),
                ('emails', models.EmailField(max_length=254)),
            ],
        ),
    ]
