# Generated by Django 2.2.12 on 2020-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='emails',
            field=models.TextField(),
        ),
    ]
