# Generated by Django 2.2.12 on 2020-04-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0002_auto_20200402_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processos',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='descricao_atualizacao',
        ),
        migrations.RemoveField(
            model_name='processos',
            name='incidente_id',
        ),
    ]
