# Generated by Django 2.2.12 on 2020-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0003_auto_20200402_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='data_atualizacao',
            field=models.TextField(default='02/04/2020'),
        ),
        migrations.AddField(
            model_name='processos',
            name='descricao_atualizacao',
            field=models.TextField(default='desc_at'),
        ),
        migrations.AddField(
            model_name='processos',
            name='incidente_id',
            field=models.TextField(default='id'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='emails',
            field=models.TextField(default='globomonitoracao@gmail.com'),
        ),
    ]
