# Generated by Django 2.2.12 on 2020-04-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0006_auto_20200402_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos',
            name='url',
            field=models.TextField(blank=True, default='url'),
        ),
    ]
