# Generated by Django 2.2.12 on 2020-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0007_processos_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='incidente_id',
            field=models.TextField(default='id'),
        ),
    ]
