# Generated by Django 2.2.12 on 2020-04-22 23:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_a_processos', '0011_auto_20200414_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processos',
            name='data_atualizacao',
            field=models.TextField(blank=True, default='03/10/1995'),
        ),
        migrations.AlterField(
            model_name='processos',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8),
        ),
    ]
